apiVersion: apps/v1
kind: Deployment
metadata:
  name: xd-web-app
  namespace: xd
  labels:
    app: xd-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xd-web-app
  template:
    metadata:
      labels:
        app: xd-web-app
    spec:
      containers:
      - name: xd-web-app
        image: dwachholder/xd-web-app
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
